config/routes.rb
Rails.application.routes.draw do
  get 'away_riders/index'
  get 'home_riders/index'
  get 'homeriders/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'meetings#index'
  resources :meetings do
    resources :home_riders
    resources :away_riders
  end
  
  resources :races
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/away_rider.rb
class AwayRider < ApplicationRecord
  belongs_to :meeting
end

app/models/home_rider.rb
class HomeRider < ApplicationRecord
  belongs_to :meeting
end

app/models/meeting.rb
class Meeting < ApplicationRecord
    validates :home_team, :away_team, presence: true
    has_many :races, dependent: :destroy
    has_many :home_riders, inverse_of: :meeting, dependent: :destroy
    accepts_nested_attributes_for :home_riders
    has_many :away_riders, inverse_of: :meeting, dependent: :destroy
    accepts_nested_attributes_for :away_riders
end

app/models/race.rb
class Race < ApplicationRecord
  belongs_to :meeting
  validates :meeting_id, :heat_number, :blue_score, :red_score, :white_score, :yellow_score, :heat_time, presence: true
  validates :blue_score, :red_score, :white_score, :yellow_score, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 3}
  validates :heat_number, numericality: {less_than_or_equal_to: 15}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/away_riders_controller.rb
class AwayRidersController < ApplicationController
  def index
    @meeting = Meeting.find(params[:meeting_id])
    @riders = @meeting.away_riders
  end
end

app/controllers/home_riders_controller.rb
class HomeRidersController < ApplicationController
  
  def index
    @meeting = Meeting.find(params[:meeting_id])
    @riders = @meeting.home_riders
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
    
    def index
        @meetings = Meeting.all
    end
    
    def new
        @meeting = Meeting.new
        7.times {@meeting.home_riders.build}
        7.times {@meeting.away_riders.build}
    end
    
    def create
        @meeting = Meeting.create(meeting_params)
        if @meeting.save
            flash[:success] = "Meeting created"
            redirect_to @meeting
        else
            flash[:alert] = "Try again!"
            render :new
        end
    end
    
    def show
        @meeting = Meeting.find(params[:id]) 
        blue_total = Race.where(meeting_id: params[:id]).sum(:blue_score)
        red_total = Race.where(meeting_id: params[:id]).sum(:red_score)
        white_total = Race.where(meeting_id: params[:id]).sum(:white_score)
        yellow_total = Race.where(meeting_id: params[:id]).sum(:yellow_score)
        @meeting.home_score = blue_total + red_total
        @meeting.away_score = white_total + yellow_total
    end
    

    def edit
        @meeting = Meeting.find(params[:id])
    end
    
    def update
        @meeting = Meeting.find(params[:id])
        @meeting.update(meeting_params)
        redirect_to(meeting_path(@meeting))
    end
    
    def destroy
      @meeting = Meeting.find(params[:id])
      @meeting.destroy
      redirect_to meetings_path
    end
    
    private
    
    def meeting_params
        params.require(:meeting).permit(:meeting_date, :home_team, :away_team, home_riders_attributes:[:name], away_riders_attributes:[:name])
    end
    
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
    
    def new
        @race = Race.new(:meeting_id => params[:meeting_id])
        heat = Race.last
        heat ? @race.heat_number = heat.heat_number + 1 : @race.heat_number = 1
    end
    
    def show
        @race = Race.find(params[:id])
    end
    
    def edit
        @race = Race.find(params[:id])
    end
    
    def update
        @race = Race.find(params[:id])
        @race.update(races_params)
        redirect_to(meeting_path(@race.meeting_id))
    end
    
    def destroy
      @race = Race.find(params[:id])
      meeting_id = @race.meeting_id
      @race.destroy
      redirect_to(meeting_path(@race.meeting_id))
    end
    
    def create
        @race = Race.create(races_params)
        if @race.save
            flash[:success] = "Race created"
            redirect_to (meeting_path(@race.meeting_id))
        else
            flash[:alert] = "Try again!"
            render :new
        end
    end
    
    private
    def races_params
        params.require(:race).permit(:heat_time, :blue_score, :red_score, :white_score, :yellow_score, :heat_number, :meeting_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/away_riders_helper.rb
module AwayRidersHelper
end

app/helpers/home_riders_helper.rb
module HomeRidersHelper
end

app/helpers/homeriders_helper.rb
module HomeridersHelper
end

app/helpers/hometeam_helper.rb
module HometeamHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/away_riders/index.html.erb
<h3><%= @meeting.away_team %> team</h3>

<%= @riders.each do |r| %>
<p></p>
<%= r.rider_name %>
<% end %>

app/views/home_riders/index.html.erb
<h3><%= @meeting.home_team %> team</h3>

<%= @riders.each do |r| %>
<p></p>
<%= r.rider_name %>
<% end %>
<p></p>
<%= link_to 'Back', :back %>
<p></p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand">Speedway Scorecard</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Meetings', meetings_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Score</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    
    
    
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    
  </body>
</html>

app/views/meetings/_form.html.erb
<%= simple_form_for @meeting do |f| %>
    <%= f.input :meeting_date %>
    <%= f.input :home_team %>
    
        <%= f.simple_fields_for :home_riders do |h| %>
            <%= h.input :name %>
        <% end %>
    
    <%= f.input :away_team %>
    
        <%= f.simple_fields_for :away_riders do |a| %>
            <%= a.input :name %>
        <% end %>
        
    <%= f.button :submit %>
<% end %>

app/views/meetings/edit.html.erb
<h3>Edit meeting</h3>

<%= render 'form' %>

app/views/meetings/index.html.erb
<p></p>
<div class="table table-bordered">
    <table>
        <thead class="thead-dark">
            <tr>
                <th>Meeting date</th>
                <th>Home team</th>
                <th>Away team</th>
                <th colspan="3"></th>
            </tr>
        </thead>
        <tbody>
            <%  @meetings.each do |meeting| %>
            <tr>
                <td><%= meeting.meeting_date.strftime("%A %B %C %G") %></td>
                <td><%= meeting.home_team %></td>
                <td><%= meeting.away_team %></td>
                <td><%= link_to 'Show', meeting %></td>
                <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
                <td><%= link_to 'Delete', meeting, method: :delete,
                                     data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>

        </tbody>
    </table>
</div>

<%= link_to "New meeting", new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New meeting</h1>

<%= render 'form' %>

app/views/meetings/show.html.erb
<div class="table-responsive">
    <div class="table table-borderless">
        <table>
            <thead>
                <tr >
                    <th colspan = "3">Meeting: <%= @meeting.meeting_date.strftime("%A %B %C") %></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><%= link_to (@meeting.home_team), meeting_home_riders_path(:meeting_id => @meeting.id) %>:</td>
                    <td><%= @meeting.home_score %></td>
                    <td><%= link_to (@meeting.away_team), meeting_away_riders_path(:meeting_id => @meeting.id) %>:</td>
                    <td><%= @meeting.away_score %></td>
                </tr>
                <tr>
                    
                </tr>
            </tbody>
        </table>
    </div>
</div>

<%= button_to "Add heat", new_race_path, params: {:meeting_id => @meeting.id}, method: :get, class: "btn btn-primary" %>

<p></p>

<div class="table table-bordered">
    <table>
        <thead class="thead-dark">
            <tr>
                <th>Heat</th>
                <th>Blue</th>
                <th>Red</th>
                <th>White</th>
                <th>Yellow</th>
                <th>Heat time</th>
                <th colspan="2"></th>
            </tr>
        </thead>
        <tbody>
            <% @meeting.races.each do |race| %>
            <tr>
                <td><%= race.heat_number %></td>
                <td><%= race.blue_score %></td>
                <td><%= race.red_score %></td>
                <td><%= race.white_score %></td>
                <td><%= race.yellow_score %></td>
                <td><%= race.heat_time %></td>
                <td><%= link_to 'Edit', edit_race_path(race) %></td>
                <td><%= link_to 'Delete', race, method: :delete,
                                     data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

<%= link_to "Back", meetings_path %>

app/views/races/_form.html.erb
<%= simple_form_for @race do |r| %>
    <%= r.input :heat_time %>
    <%= r.input :blue_score, input_html: { style: 'background-color: aliceblue' }  %>
    <%= r.input :red_score, input_html: { style: 'background-color: pink' } %>
    <%= r.input :white_score %>
    <%= r.input :yellow_score, input_html: { style: 'background-color: lemonchiffon' } %>
    <%= r.hidden_field :heat_number %>
    <%= r.hidden_field :meeting_id %>
    <%= r.button :submit %>
<% end %>

app/views/races/edit.html.erb
<h3>Edit race</h3>

<%= render 'form' %>

app/views/races/new.html.erb
<h3>New race</h3>
<h3>Heat: <%= @race.heat_number %></h3>

<%= render 'form' %>

app/views/races/show.html.erb
<h1>Show race</h1>
<div class="table table-bordered">
    <table>
        <thead class="thead-dark">
            <tr>
                <th>Heat</th>
                <th>Blue</th>
                <th>Red</th>
                <th>White</th>
                <th>Yellow</th>
                <th>Heat time</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><%= @race.heat_number %></td>
                <td><%= @race.blue_score %></td>
                <td><%= @race.red_score %></td>
                <td><%= @race.white_score %></td>
                <td><%= @race.yellow_score %></td>
                <td><%= @race.heat_time %></td>
            </tr>
        </tbody>
    </table>
</div>

<%= link_to "Back", race_path %>